WIP: Fix panic on Android app reopen
gfx-rs/gfx pull request #3754
Opened 2021-05-09 18:10 UTC by zakorgy

Fixes #https://github.com/gfx-rs/gfx/issues/3420
I still have to test this on Android. Also I wasn't sure that changing `capabilities` to return with a `Result` thus adding an API change would be the proper way to do this, so I just put some `default`s there.
PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:

2021-05-09 18:45 UTC, Gordon-F commented on src/backend/vulkan/src/window.rs
> +                    Err(vk::Result::ERROR_SURFACE_LOST_KHR) => vk::SurfaceCapabilitiesKHR::default(),
It would be great to log some warning here. And in other places with same logic.

2021-05-10 03:37 UTC, kvark requested changes
Thank you for addressing this!
We'll need one more iteration on the code :)

2021-05-10 03:37 UTC, kvark commented on src/backend/vulkan/src/window.rs
> +                    Err(vk::Result::ERROR_SURFACE_LOST_KHR) => return None,
This is a bit more tricky, unfortunately. `None` result means that all formats are supported. Is this really what we want to report if the surface is lost? I think returning `Some(Vec::new())` would be a little better

2021-05-10 03:37 UTC, kvark commented on src/backend/vulkan/src/window.rs
> +                    #[cfg(target_os = "android")]
let's not have this on Android only, let's have this everywhere

2021-05-10 03:37 UTC, kvark commented on src/backend/vulkan/src/window.rs
> +                    #[cfg(target_os = "android")]
same here, we can have this code on all platforms

2021-05-10 03:37 UTC, kvark commented on src/backend/vulkan/src/window.rs
> +                    Err(vk::Result::ERROR_SURFACE_LOST_KHR) => vec![vk::PresentModeKHR::default()],
would it make sense to return an empty vector here?

2021-05-10 18:28 UTC, kvark approved these changes

2021-05-10 18:29 UTC, kvark commented
bors r+

2021-05-10 18:39 UTC, merged